# Generated by Django 5.2.7 on 2025-10-04 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 4, 10, 52, 23, 422682, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
